server:
  port: 8082
  servlet:
    context-path: '/secretaria/'

spring:
  application:
    name: secretaria
  datasource:
    url: jdbc:postgresql://localhost:5432/secretaria
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
